### ISSUE TITLE
Key error in for-loops when using 'rename_for_loop_variables' option

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#128]
### What happened?

Decompiler hard crashes with an `key-error` in a for-loop with array accesses in code block and "complex" modification statement. 

```python
Traceback (most recent call last):
  File "/home/user/Git-Repos/__DewolfTesting/../DeWolf/decompile.py", line 80, in <module>
    main(Decompiler)
  File "/home/user/Git-Repos/DeWolf/decompiler/util/commandline.py", line 65, in main
    task = decompiler.decompile(function_name, options)
  File "/home/user/Git-Repos/__DewolfTesting/../DeWolf/decompile.py", line 56, in decompile
    task.code = self._backend.generate([task])
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codegenerator.py", line 32, in generate
    string_blocks.append(self.generate_function(task))
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codegenerator.py", line 42, in generate_function
    function_body=CodeVisitor(task).visit(task.syntax_tree.root) if not task.failed else task.failure_message,
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/visitors/interfaces.py", line 18, in visit
    return node.accept(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/ast/ast_nodes.py", line 310, in accept
    return visitor.visit_seq_node(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 46, in visit_seq_node
    return "".join(map(self.visit, node.children))
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/visitors/interfaces.py", line 18, in visit
    return node.accept(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/ast/ast_nodes.py", line 731, in accept
    return visitor.visit_loop_node(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 65, in visit_loop_node
    return f"{loop_type}{{{self.visit(node.body)}}}{loop_after}"
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/visitors/interfaces.py", line 18, in visit
    return node.accept(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/ast/ast_nodes.py", line 421, in accept
    return visitor.visit_code_node(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 112, in visit_code_node
    return "\n".join(map(stmt_string, node.instructions))
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 110, in stmt_string
    return f"{self.visit(stmt)};"
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/visitors/interfaces.py", line 18, in visit
    return node.accept(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/pseudo/instructions.py", line 199, in accept
    return visitor.visit_assignment(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 121, in visit_assignment
    return super(CodeVisitor, self).visit_assignment(instr)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/cexpressiongenerator.py", line 261, in visit_assignment
    return f"{self.visit(instr.destination)} = {self.visit(instr.value)}"
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/visitors/interfaces.py", line 18, in visit
    return node.accept(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/structures/pseudo/operations.py", line 367, in accept
    return visitor.visit_unary_operation(self)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 128, in visit_unary_operation
    return self._visit_array_element_access(op)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 137, in _visit_array_element_access
    base, index = self._parse_array_element_access_attributes(array_elem_access)
  File "/home/user/Git-Repos/DeWolf/decompiler/backend/codevisitor.py", line 156, in _parse_array_element_access_attributes
    ssa_name_to_name_mapping[array_elem_access.array_info.index.name]
KeyError: 'var_14'
```

### How to reproduce?

Tried to decompile a for-loop with a "complex" modification statement (/=) __and__ an array access in the body. 
Error only occurs when `rename_for_loop_variables` is enabled. 

```C
int main(){
    char *ptr = calloc(1000, sizeof(char));

    for(int i = 512; i > 0; i /= 2){
        ptr[i] = i;
    }

    free(ptr);

    return 0;
}
```

### Affected Binary Ninja Version(s)

3.2.3814 (Build ID f851a8ee)

**Comment by mm4rks** [comment]
Can not reproduce on commit b2aa6674, 3.2.3814 (Build ID f851a8ee).
Output:



```c
int main(int argc, char ** argv, char ** envp) {
    int i;
    void * var_0;
    var_0 = calloc(/* n */ 0x3e8, /* elem_size */ 1UL);
    for (i = 0x200; i > 0; i = i + (i >> 31) >> 1) {
        *(var_0 + i) = i;
    }
    free(/* mem */ var_0);
    return 0;
}
```

**Comment by NeoQuix** [comment]
A newer commit added the option `array-access-detection`, which defaults to show array accesses as 
`*(ptr + offset)`, instead of `ptr[offset]` when the type is known. 

Change in `array-access-detection` default to true instead of false. 
After that the error should appear again.
