### ISSUE TITLE
Fix binaryninja function iteration

### ISSUE THREAD

**Issue by 0x6e62** [fkie-cad/dewolf#142]
### What happened?

When we fetch the functions in a given binary from binaryninja, a NoneType object is returned, crashing the pipeline at the start.

### How to reproduce?

`python decompile.py 4e1202aaae28344b4d11da3839d845a2f51c3e4112ae0e4c1ba726c3d2fbc477`
will result in 

```
Traceback (most recent call last):
  File "/home/nb/workspace/dream#/dewolf/decompile.py", line 80, in <module>
    main(Decompiler)
  File "/home/nb/workspace/dream#/dewolf/decompiler/util/commandline.py", line 59, in main
    undecorated_code = decompiler.decompile_all(options)
  File "/home/nb/workspace/dream#/dewolf/decompile.py", line 69, in decompile_all
    task = self._frontend.create_task(function, task_options)
  File "/home/nb/workspace/dream#/dewolf/decompiler/frontend/binaryninja/frontend.py", line 57, in create_task
    return_type, params = self._extract_return_type_and_params(function)
  File "/home/nb/workspace/dream#/dewolf/decompiler/frontend/binaryninja/frontend.py", line 94, in _extract_return_type_and_params
    params: List[Variable] = [lifter.lift(param) for param in function.function_type.parameters]
AttributeError: 'NoneType' object has no attribute 'function_type'
```

### Affected Binary Ninja Version(s)

3.2.3857

**Comment by mm4rks** [comment]
Can you provide a crashing sample?
