### ISSUE TITLE
[Readability based refinement] AttributeError: 'ListOperation' object has no attribute ssa_name

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#207]
### What happened?

```python
Error in bin/refsutil.exe in 0x140001e74
[pipeline.py:107 run()] ERROR - Failed to decompile wmain, error during stage readability-based-refinement: 'ListOperation' object has no attribute 'ssa_name'
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/readability_based_refinement.py", line 469, in run
    ForLoopVariableRenamer(task.syntax_tree, variableNames).rename()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/readability_based_refinement.py", line 432, in rename
    new_variable = Variable(self._get_variable_name(), old_variable.type, ssa_name=old_variable.ssa_name)
AttributeError: 'ListOperation' object has no attribute 'ssa_name'
```

### How to reproduce?

Decompile [refsutil](https://github.com/fkie-cad/dewolf/files/11168479/refsutil.tar.gz) in 0x140001e74.

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by NeoQuix** [comment]
Code: `arg1 = *((*(rdi#6)) + 0x8)(var_31, arg2 + 0x10, (unsigned int) arg1 + -0x2, &(var_21), 0x3, var_23)`

Type is correct, but the code does not expect a function result as a for loop declaration. 
Maybe just don't accept ListOperation as a `_get_variable_initialisation`, resulting in no declaration, thus preventing the error. 

Or accept fkt calls + change for_loop_renamer + code generator for for_loops

**Comment by NeoQuix** [comment]
Code: Z.145 in readability_based_ref `if variable in instruction.definitions and not isinstance(instruction.destination, ListOperation):` (maybe do a type check for Assignment to have the correct typing)
