### ISSUE TITLE
[Pseudo logic; Dead path elim] Cannot convert float infinity to integer 

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#211]
### What happened?

```python3
Error in bin/mcbuilder.exe in 0x14000a3e0
[pipeline.py:107 run()] ERROR - Failed to decompile log10, error during stage dead-path-elimination: cannot convert float infinity to integer
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/dataflowanalysis/dead_path_elimination.py", line 35, in run
    if not (dead_edges := set(self.find_unsatisfyable_edges(task.graph))):
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/dataflowanalysis/dead_path_elimination.py", line 65, in find_unsatisfyable_edges
    if dead_edge := self._get_invalid_branch_edge(graph, branch_block, branch_instruction):
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/dataflowanalysis/dead_path_elimination.py", line 71, in _get_invalid_branch_edge
    condition = self._logic_converter.convert(instruction, define_expr=True)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/logic.py", line 29, in convert
    return self._convert_branch(expression)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 71, in _convert_branch
    return self._convert_condition(branch.condition)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 80, in _convert_condition
    _operation = self._get_operation(condition)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in _get_operation
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in <listcomp>
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/logic.py", line 33, in convert
    return self._convert_operation(expression)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 89, in _convert_operation
    _operation = self._get_operation(operation)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in _get_operation
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in <listcomp>
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/logic.py", line 31, in convert
    return self._convert_condition(expression)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 80, in _convert_condition
    _operation = self._get_operation(condition)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in _get_operation
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in <listcomp>
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/logic.py", line 33, in convert
    return self._convert_operation(expression)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 89, in _convert_operation
    _operation = self._get_operation(operation)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in _get_operation
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 94, in <listcomp>
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/logic.py", line 27, in convert
    return self._convert_constant(expression)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/pseudo/z3_logic.py", line 61, in _convert_constant
    return BitVecVal(constant.value, constant.type.size if constant.type.size else 32, ctx=self._context)
  File "/home/neoquix/Git-Repos/DeWolf/.venv/lib/python3.10/site-packages/z3/z3.py", line 3809, in BitVecVal
    return BitVecNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), BitVecSort(bv, ctx).ast), ctx)
  File "/home/neoquix/Git-Repos/DeWolf/.venv/lib/python3.10/site-packages/z3/z3.py", line 2976, in _to_int_str
    return str(int(val))
OverflowError: cannot convert float infinity to integer
```

### How to reproduce?

Decompile [mcbuilder](https://github.com/fkie-cad/dewolf/files/11168727/mcbuilder.tar.gz) at 0x14000a3e0

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by NeoQuix** [comment]
MIL from bninja actually wants `MLIL_FLOAT_CONV` to be `inf`. 
Will be lifted by `lift_constant` to a `Constant(inf)`. 

(Later the value will be propagated into the if condition below)

Ähhh actually no idea what is happening. 
Not really into x86 float assembly. 

For debug: Block 0x02, name z#1
