### ISSUE TITLE
[Pattern independent restructuring] TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#212]
### What happened?

```python3
Error in bin/vds.exe in 0x14002ae90
[pipeline.py:107 run()] ERROR - Failed to decompile ?QueryMaxReclaimableBytes@CVdsVolume@@UEAAJPEA_K@Z, error during stage pattern-independent-restructuring: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring.py", line 45, in run
    self.restructure_cfg()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring.py", line 81, in restructure_cfg
    AcyclicRegionRestructurer(self.t_cfg, self.asforest).restructure()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 44, in restructure
    self._construct_ast_for_region(restructurable_region, node)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 69, in _construct_ast_for_region
    restructured_region_root = self._construct_refined_ast(seq_node)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 94, in _construct_refined_ast
    ConditionAwareRefinement.refine(self.asforest)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement.py", line 40, in refine
    stage(asforest)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py", line 45, in construct
    initial_switch_constructor._try_to_construct_initial_switch_node_for(seq_node)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py", line 68, in _try_to_construct_initial_switch_node_for
    self._add_constants_to_cases(switch_node, case_dependency)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py", line 172, in _add_constants_to_cases
    self._get_linear_order_for(cross_nodes, linear_ordering_starting_at, linear_order_dependency_graph)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py", line 374, in _get_linear_order_for
    first_node, last_node = self._order_parallel_cases(case_nodes_to_order, linear_ordering_starting_at)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py", line 402, in _order_parallel_cases
    sorted_case_nodes = sorted(case_nodes, key=lambda case_node: case_node.constant.value)
TypeError: '<' not supported between instances of 'int' and 'str'
```

### How to reproduce?

Decompile [vds](https://github.com/fkie-cad/dewolf/files/11168825/vds.tar.gz) at 0x14002ae90.

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by NeoQuix** [comment]
In `initial_switch_node_constructer.py` L.244 the reaching condition is set to a fixed string. 
It implies, that the node _should_(?) be merged to the previous case, but is not done afterwards? 

Probably a case merge is missing in the algorithm?

**Comment by NeoQuix** [comment]
Maybe fixed with #114. 
Blocked until.

**Comment by ebehner** [comment]
@fkie-cad/decompiler seems to work, can we close this?

**Comment by NeoQuix** [comment]
Would close it too
