### ISSUE TITLE
[Missing definitions] Every non-aliased variable should be defined, but variable has no definition.

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#215]
### What happened?

```python
Error in bin/sacsess.exe in 0x140003750
[pipeline.py:107 run()] ERROR - Failed to decompile ?Write@CVTUTF8Scraper@@UEAAHXZ, error during stage insert-missing-definitions: Every non-aliased variable should be defined, but variable rdx_2#4 has no definition.
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/missing_definitions.py", line 99, in run
    self.insert_missing_definitions()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/missing_definitions.py", line 133, in insert_missing_definitions
    self._insert_definition_if_undefined(variable, previous_ssa_labels, undefined_variables)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/missing_definitions.py", line 157, in _insert_definition_if_undefined
    raise ValueError(f"Every non-aliased variable should be defined, but variable {variable} has no definition.")
ValueError: Every non-aliased variable should be defined, but variable rdx_2#4 has no definition.
```

### How to reproduce?

Decompile [sacsess](https://github.com/fkie-cad/dewolf/files/11168987/sacsess.tar.gz) at 0x140003750.

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by ebehner** [comment]
The problem is that the phi-function for variable `rdx_2#4` is missing. Having a look at the program in MLIL, one can see that `rdx_2` is defined twice, and two different definitions can reach the usage in the "last" block:
![issue_215_non_ssa](https://user-images.githubusercontent.com/7224664/234779520-c894f9c0-b901-42f9-97e0-61c43a4cce27.png)

Now, in MLIL SSA-form, Binary Ninja assign different SSA-labels for the two definitions and another one for the usage. However, the phi-function at the beginning of the block is missing. There is only the phi-function for `rdx_3#4 = phi(rdx_2#2, rdx_2#3)`, but there should also be the phi-function `rdx_2#4 = phi(rdx_2#2, rdx_2#3)`:
![issue_215_ssa_form](https://user-images.githubusercontent.com/7224664/234779932-3987c9b7-4f85-402d-941f-27d69b778d2e.png)

We have two options:
1. We say it is a Binary Ninja problem and ignore it or write an Issue 
2. We update the missing definitions algorithm and introduce such phi-functions by our own.

**Comment by ebehner** [comment]
preferable, binary ninja issue 
block issue until fixed by binary ninja, if they will not do it, we will try to solve it by our own.

**Comment by NeoQuix** [comment]
Will block for now and create a bninja issue later.

**Comment by NeoQuix** [comment]
Upstream: https://github.com/Vector35/binaryninja-api/issues/4546
