### ISSUE TITLE
[Switch variable detection] No switch variable candidate found

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#217]
### What happened?

```python
Error in bin/esentutl.exe in 0x140002c20
[pipeline.py:107 run()] ERROR - Failed to decompile ?ErrPrintField@@YAJQEBUESEUTIL_SPACE_DUMP_CTX@@QEBU_BTREE_STATS@@QEBU_BTREE_POST_COMPUTED_SPACE_STATS@@K@Z, error during stage backward-slice-switch-variable-detection: No switch variable candidate found.
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 91, in run
    self._handle_switch_block(switch_block)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 106, in _handle_switch_block
    switch_expression = self.find_switch_expression(switch_instruction)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 117, in find_switch_expression
    raise ValueError("No switch variable candidate found.")
ValueError: No switch variable candidate found.
```

### How to reproduce?

Decompile [esentutl](https://github.com/fkie-cad/dewolf/files/11169201/esentutl.tar.gz) at 0x140002c20

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by ebehner** [comment]
could be related to #284

**Comment by mm4rks** [comment]
Backward slice of switch variable ends in undefined variable (`arg_28#0`). We could assume that only globals and function arguments are not not defined in the current cfg and allow switching on undef variables...
