### ISSUE TITLE
[Pattern independent restructuring] ValueError: The children of Sequence can not be sorted due to circular reachability

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#218]
### What happened?

```python
Error in bin/WMIC.exe in 0x1400355a4
[pipeline.py:107 run()] ERROR - Failed to decompile ?ParseAssocSwitchEx@CParserEngine@@AEAA?AW4tag_RETCODE@@AEAV?$vector@PEAGV?$allocator@PEAG@std@@@std@@AEAV?$_Vector_iterator@PEAGV?$allocator@PEAG@std@@@4@AEAVCParsedInfo@@W4tag_ASSOCSwitch@@@Z, error during stage pattern-independent-restructuring: The children of Sequence can not be sorted due to circular reachability
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring.py", line 45, in run
    self.restructure_cfg()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring.py", line 81, in restructure_cfg
    AcyclicRegionRestructurer(self.t_cfg, self.asforest).restructure()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 44, in restructure
    self._construct_ast_for_region(restructurable_region, node)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 69, in _construct_ast_for_region
    restructured_region_root = self._construct_refined_ast(seq_node)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/acyclic_restructuring.py", line 95, in _construct_refined_ast
    acyclic_processor.postprocess_condition_refinement()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/restructuring_commons/ast_processor.py", line 138, in postprocess_condition_refinement
    self.asforest.combine_cascading_single_branch_conditions(self.asforest.current_root)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/syntaxforest.py", line 396, in combine_cascading_single_branch_conditions
    for condition_node in self.get_condition_nodes_post_order(root):
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/syntaxgraph.py", line 186, in get_condition_nodes_post_order
    yield from self._iter_post_order(root, lambda x: isinstance(x, ConditionNode))
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/syntaxgraph.py", line 158, in _iter_post_order
    for node in self.post_order(src):
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/syntaxgraph.py", line 123, in post_order
    yield from self._post_order(source)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/syntaxgraph.py", line 132, in _post_order
    for child in source.children:
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/ast_nodes.py", line 276, in children
    self.sort_children()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/structures/ast/ast_nodes.py", line 284, in sort_children
    raise ValueError(f"The children of {self} can not be sorted due to circular reachability")
ValueError: The children of Sequence can not be sorted due to circular reachability
```

### How to reproduce?

Decompile [WMIC](https://github.com/fkie-cad/dewolf/files/11169215/WMIC.tar.gz) at 0x1400355a4

### Affected Binary Ninja Version(s)

3.3.3996

**Comment by ebehner** [comment]
This can be solved by changing the `and` to an `or` in https://github.com/fkie-cad/dewolf/blob/bdb0eacbfc335b0a6f69e419e80b3a84801ff411/decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/missing_case_finder.py#L350.

If there is a path, not matter which, then we can not merge these two nodes because there exists a node that must be before and after the switch node after merging the case with the switch.

**Comment by mm4rks** [comment]
https://bugfinder.seclab-bonn.de/case/476083/

duplicate: https://github.com/fkie-cad/dewolf/issues/249
