### ISSUE TITLE
[variable-name-generation]  Fix various small bugs in hungarian notation

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#235]
### What happened?

1. `CustomType` variables will be renamed to `NoneVar1`
2.  Keep names from `InstructionLengthHandler` (temp_1)
3.  KeyError 104 in:
```python
Traceback (most recent call last):
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/neoquix/Git-Repos/DeWolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py", line 174, in run
    renamer.renameVariableNames()
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py", line 111, in renameVariableNames
    var._name = self._hungarian_notation(var, counter if counter else "")
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py", line 116, in _hungarian_notation
    return f"{self._hungarian_prefix(var.type)}{self._type_separator}{self._var_name}{self._counter_separator}{counter}"
  File "/home/neoquix/Git-Repos/DeWolf/decompiler/pipeline/controlflowanalysis/variable_name_generation.py", line 132, in _hungarian_prefix
    prefix = self.type_prefix[type(var_type)][var_type.size]
KeyError: 104

```

### How to reproduce?

1/2 in various bins, 3 in `shred` main. 

### Affected Binary Ninja Version(s)

-

**Comment by NeoQuix** [comment]
BNinja trolling again. 
The variable from error 3 is __really__ a `int104_t`.
Totally bninja type error, because `movaps` always works with 16 byte data.

==> make a default case for dic
==> but what as a default value?

**Comment by NeoQuix** [comment]
There are no "defaults" in hungarian (in src the type is always known), therefore how about:
- "unk" for unknown types (like int104_t)
- "cm" for custom types
