### ISSUE TITLE
[ValueError@switch_variable_detection.py:117] ValueError: No switch variable candidate found. But with actual switch.

### ISSUE THREAD

**Issue by mm4rks** [fkie-cad/dewolf#306]
### What happened?

```python
Traceback (most recent call last):
  File "/home/user/dewolf/decompile.py", line 76, in <module>
    main(Decompiler)
  File "/home/user/dewolf/decompiler/util/commandline.py", line 80, in main
    task = decompiler.decompile(function_name, options)
  File "/home/user/dewolf/decompile.py", line 51, in decompile
    pipeline.run(task)
  File "/home/user/dewolf/decompiler/pipeline/pipeline.py", line 109, in run
    raise e
  File "/home/user/dewolf/decompiler/pipeline/pipeline.py", line 102, in run
    instance.run(task)
  File "/home/user/dewolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 91, in run
    self._handle_switch_block(switch_block)
  File "/home/user/dewolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 106, in _handle_switch_block
    switch_expression = self.find_switch_expression(switch_instruction)
  File "/home/user/dewolf/decompiler/pipeline/preprocessing/switch_variable_detection.py", line 117, in find_switch_expression
    raise ValueError("No switch variable candidate found.")
ValueError: No switch variable candidate found.
```

### How to reproduce?
```rust
pub fn test1(day: usize) {
    match day {
        1 => println!("Monady"),
        2 => println!("Tuesday"),
        3 => {},
        4 => println!("Thursday"),
        5 => println!("Friday"),
        6 => println!("Saturday"),
        7 => println!("Sunday"),
        _ => println!("Invalid input")
    }
}
```

[sample.zip](https://github.com/fkie-cad/dewolf/files/12269258/sample.zip)

 ```
dewolf rustTest.exe sub_140001020 --debug -v
```

### Affected Binary Ninja Version(s)

3.4.4271

**Comment by mm4rks** [comment]
related: #279

**Comment by mm4rks** [comment]
![rust](https://github.com/fkie-cad/dewolf/assets/65773903/9d1638af-7c6f-4345-80dd-e4a20f832c76)

switching on day#0 (function arg) seems to be correct. However, `_is_bounds_checked` fails due to arguments not being in defmap.
