### ISSUE TITLE
ModuleNotFoundError: No module named 'simplifier' when running decompile.py in command line

### ISSUE THREAD

**Issue by yangzao** [fkie-cad/dewolf#378]
### Question

Hi,

I tried to run the CLI version of dewolf (decompile.py), but it's showing no module named 'simplifier':
```
zao@lebowski:~/code/decompilers/dewolf$ python3 decompile.py --help
Traceback (most recent call last):
  File "/home/zao/code/decompilers/dewolf/decompile.py", line 7, in <module>
    from decompiler.backend.codegenerator import CodeGenerator
  File "/home/zao/code/decompilers/dewolf/decompiler/backend/codegenerator.py", line 5, in <module>
    from decompiler.backend.cexpressiongenerator import CExpressionGenerator
  File "/home/zao/code/decompilers/dewolf/decompiler/backend/cexpressiongenerator.py", line 4, in <module>
    from decompiler.structures import pseudo as expressions
  File "/home/zao/code/decompilers/dewolf/decompiler/structures/pseudo/__init__.py", line 2, in <module>
    from .delogic_logic import DelogicConverter
  File "/home/zao/code/decompilers/dewolf/decompiler/structures/pseudo/delogic_logic.py", line 6, in <module>
    from simplifier.world.nodes import Variable as WorldVariable
ModuleNotFoundError: No module named 'simplifier'
```
I couldn't find this module in pip3 or online. Is this module from BinaryNinja, or is there anything I'm missing?

**Comment by steffenenders** [comment]
Hi!

Hm, it seems like you did not install the dewolf-logic module from https://github.com/fkie-cad/dewolf-logic
Have you followed the installation steps from the Readme, i.e. installing the requirements using pip? If not, make sure to `pip install -r requirements.txt`
Also, take a look at the following issue+solution from a seemingly related issue: https://github.com/fkie-cad/dewolf/issues/345

**Comment by yangzao** [comment]
thank you!
