### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'subexpressions'

### ISSUE THREAD

**Issue by 19h** [fkie-cad/dewolf#385]
### What happened?

Not sure how to properly pin this down:

```
Decompilation of `__ZN3geo5codec15_readCoastlinesEP8VMP4TileRKNSt3__110shared_ptrINS0_10VectorTileEEE` failed with:

<class 'AttributeError'>

'NoneType' object has no attribute 'subexpressions'

Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompiler/util/widget.py", line 51, in run
    code = self.decompile_for_widget(self.binary_view, self.function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompiler/util/widget.py", line 67, in decompile_for_widget
    task = decompiler.decompile(function, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompile.py", line 52, in decompile
    task.code = self._backend.generate([task])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompiler/backend/codegenerator.py", line 30, in generate
    string_blocks.append(GlobalDeclarationGenerator.from_asts(task.syntax_tree for task in tasks if not task.failed))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompiler/backend/variabledeclarations.py", line 65, in from_asts
    global_variables, extern_constants = GlobalDeclarationGenerator._get_global_variables_and_constants(asts)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/dewolf/decompiler/backend/variabledeclarations.py", line 89, in _get_global_variables_and_constants
    for expression in obj.subexpressions():
                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'subexpressions'
```

### How to reproduce?

Compiling the function `__ZN3geo5codec15_readCoastlinesEP8VMP4TileRKNSt3__110shared_ptrINS0_10VectorTileEEE` of:

[GeoServices.zip](https://github.com/fkie-cad/dewolf/files/14334212/GeoServices.zip)

### Affected Binary Ninja Version(s)

4.0.4886

**Comment by 19h** [comment]
From what I can see this code (https://github.com/fkie-cad/dewolf/commit/3f6701b93cac4fc8f94efcfc29860c17380c3fb5) was introduced on January 18th by @rihi and @steffenenders.

**Comment by rihi** [comment]
Does the issue persist with the latest commit on the main branch?
The code related to this error has undergone significant changes since then, and I can no longer replicate the problem.
