### ISSUE TITLE
z3 Exception: True, False or Z3 Boolean expression expected. Received 1 of type <class 'int'>

### ISSUE THREAD

**Issue by steffenenders** [fkie-cad/dewolf#70]
### What happened?

Using the old lifter, the decompiler crashes with:
```
Traceback (most recent call last):
  File "/home/user/0xff/decompiler2/decompile.py", line 78, in <module>
    main(Decompiler)
  File "/home/user/0xff/decompiler2/dewolf/util/commandline.py", line 59, in main
    undecorated_code = decompiler.decompile_all(options)
  File "/home/user/0xff/decompiler2/decompile.py", line 68, in decompile_all
    pipeline.run(task)
  File "/home/user/0xff/decompiler2/dewolf/pipeline/pipeline.py", line 97, in run
    instance.run(task)
  File "/home/user/0xff/decompiler2/dewolf/pipeline/dataflowanalysis/dead_path_elimination.py", line 30, in run
    if not (dead_edges := set(self.find_unsatisfyable_edges(task.graph))):
  File "/home/user/0xff/decompiler2/dewolf/pipeline/dataflowanalysis/dead_path_elimination.py", line 60, in find_unsatisfyable_edges
    if dead_edge := self._get_invalid_branch_edge(graph, branch_block, branch_instruction):
  File "/home/user/0xff/decompiler2/dewolf/pipeline/dataflowanalysis/dead_path_elimination.py", line 66, in _get_invalid_branch_edge
    condition = self._logic_converter.convert(instruction)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 46, in convert
    return self._convert_branch(expression)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 71, in _convert_branch
    return self._convert_condition(branch.condition)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 80, in _convert_condition
    _operation = self._get_operation(condition)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 94, in _get_operation
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 94, in <listcomp>
    operands = self._ensure_same_sort([self.convert(operand) for operand in operation.operands])
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 50, in convert
    return self._convert_operation(expression)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 89, in _convert_operation
    _operation = self._get_operation(operation)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 101, in _get_operation
    return converter(*operands)
  File "/home/user/0xff/decompiler2/dewolf/structures/pseudo/logic.py", line 156, in <lambda>
    OperationType.multiply: lambda a, b: a * b,
  File "/home/user/.local/lib/python3.9/site-packages/z3/z3.py", line 1435, in __mul__
    if other == 1:
  File "/home/user/.local/lib/python3.9/site-packages/z3/z3.py", line 946, in __eq__
    a, b = _coerce_exprs(self, other)
  File "/home/user/.local/lib/python3.9/site-packages/z3/z3.py", line 1114, in _coerce_exprs
    b = s.cast(b)
  File "/home/user/.local/lib/python3.9/site-packages/z3/z3.py", line 1409, in cast
    _z3_assert(is_expr(val), "True, False or Z3 Boolean expression expected. Received %s of type %s" % (val, type(val)))
  File "/home/user/.local/lib/python3.9/site-packages/z3/z3.py", line 96, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received 1 of type <class 'int'>
```

Using the new lifter, the decompiler crashes with:
```
Traceback (most recent call last):
  File "/Users/steffenenders/Repositories/Work/dewolf/decompile.py", line 80, in <module>
    main(Decompiler)
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/util/commandline.py", line 65, in main
    task = decompiler.decompile(function_name, options)
  File "/Users/steffenenders/Repositories/Work/dewolf/decompile.py", line 54, in decompile
    task = self._frontend.create_task(function, task_options)
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/frontend.py", line 57, in create_task
    cfg = self._extract_cfg(function, options)
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/frontend.py", line 83, in _extract_cfg
    return parser.parse(function)
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/parser.py", line 34, in parse
    index_to_BasicBlock[basic_block.index] = BasicBlock(basic_block.index, instructions=list(self._lift_instructions(basic_block)))
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/parser.py", line 77, in _lift_instructions
    if lifted_instruction := self._lifter.lift(instruction):
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/lifter.py", line 28, in lift
    if pseudo_expression := handler(expression, **kwargs):
  File "/Users/steffenenders/Repositories/Work/dewolf/decompiler/frontend/binaryninja/handlers/calls.py", line 71, in lift_intrinsic
    writes_memory=call.output_dest_memory if ssa else None,
AttributeError: 'MediumLevelILIntrinsicSsa' object has no attribute 'output_dest_memory'
```
(which appears to be the same lifter error as in #69)

### How to reproduce?

Decompile `main` from the following sample:
[742b2356-eda6-44ac-b01c-67f24f892251.bin.zip](https://github.com/fkie-cad/dewolf/files/8097466/742b2356-eda6-44ac-b01c-67f24f892251.bin.zip)

### Affected Binary Ninja Version(s)

Version 3.0.3233 (Build ID e250d0a3)

**Comment by ebehner** [comment]
blocked by Issue #69
