### ISSUE TITLE
[Lifter] Lift expression as None

### ISSUE THREAD

**Issue by ebehner** [fkie-cad/dewolf#76]
### What happened?

After updating the Lifter, we lift instructions as None leading to a ValueError in type propagation:
```bash
Traceback (most recent call last):
  File "decompile.py", line 80, in <module>
    main(Decompiler)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/util/commandline.py", line 65, in main
    task = decompiler.decompile(function_name, options)
  File "decompile.py", line 55, in decompile
    pipeline.run(task)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/pipeline/pipeline.py", line 97, in run
    instance.run(task)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/pipeline/dataflowanalysis/type_propagation.py", line 102, in run
    graph = TypeGraph.from_cfg(task.graph)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/pipeline/dataflowanalysis/type_propagation.py", line 38, in from_cfg
    graph.add_instruction(instruction)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/pipeline/dataflowanalysis/type_propagation.py", line 44, in add_instruction
    self.add_expression(top_level_expression, instruction)
  File "/home/eva/Projects/dewolf-decompiler/decompiler/pipeline/dataflowanalysis/type_propagation.py", line 63, in add_expression
    self.add_edge(self._make_node(sub_expression), self._make_node(head), label=self.EdgeType.subexpression)
  File "/home/eva/Projects/dewolf-decompiler/.venv/lib/python3.8/site-packages/networkx/classes/digraph.py", line 622, in add_edge
    raise ValueError("None cannot be a node")
ValueError: None cannot be a node
```

The problem occurs in this block:
![image](https://user-images.githubusercontent.com/7224664/155370282-65966f9a-3d0f-4202-8521-500cec78b8e4.png)

We lift these instructions as follows:
![image](https://user-images.githubusercontent.com/7224664/155370418-02accc27-0b22-4977-b8c0-598cb84b927c.png)

### How to reproduce?

[test_1.zip](https://github.com/fkie-cad/dewolf/files/8126288/test_1.zip) `main`

### Affected Binary Ninja Version(s)

3.0.3233 (Build ID e250d0a3)

**Comment by 0x6e62** [comment]
`[0x20a62b].b @ mem#4` results in `*(&(None))`

**Comment by 0x6e62** [comment]
fixing this issue by changing `_lift_global_variable` to set default variable names results in a follow-up issue.
fix:
```python
        return UnaryOperation(
            OperationType.address,
            [GlobalVariable(variable.name if variable.name else f'data_{hex(symbol.address)}', vartype=self._lifter.lift(variable.type), ssa_label=0, initial_value=initial_value)],
            vartype=Pointer(self._lifter.lift(variable.type)),
        )
```
>  File "/home/nb/workspace/dream#/dewolf/decompiler/structures/pseudo/logic.py", line 194, in <lambda>
>    OperationType.less_or_equal: lambda a, b: a <= b,
>TypeError: '<=' not supported between instances of 'BoolRef' and 'BoolRef'

**Comment by 0x6e62** [comment]
The new bug has alreadx been fixed on the most recent main branch
